linux-system-roles/template

molecule/default/Dockerfile.j2
molecule/default/molecule.yml
molecule/default/yamllint.yml

This setup is used in Molecule-enabled roles at the moment.
Next steps:
- The idea is to synchronize molecule directory from this repo into roles with script similar to:
https://github.com/cloudalchemy/auto-maintenance/blob/master/sync_skeleton.sh
- Docker images can be (re)used from:
https://github.com/paulfantom/dockerfiles
(CentOS6 needs to be added)

Add default Molecule setup.

---

molecule/default/molecule.yml

To avoid name squatting attacks/problems it is necessary to specify the
container registry when specifying a container image. Otherwise an image
with the same name from a different registry could be obtained.
References: https://raesene.github.io/blog/2019/09/25/typosquatting-in-a-multi-registry-world/

Molecule: Specify container registry

---

.travis/custom_pylint.py

Do not run `pylint` if there are no python files to be linted.

Do not run pylint with no files given

---

tasks/main.yml

As Jinja variables are expanded properly in task names, we are returning them back (this makes Ansible logs more readable).

Return back Jinja vars in task names.

---

tests/setup_module_utils.sh
tox.ini

When running pytest, pylint, etc. in tox, ensure that
imports like
import ansible.module_utils.mylocalutils
can be resolved correctly.  We rely on the fact that the
`tox` `testenv` `commands_pre` commands are run for every
test, before the actual test command.  The `commands_pre`
will run the script `tests/setup_module_utils.sh`.  This
script will see if the role has installed `ansible` in
the current tox venv, and that the role has local
`module_utils/`.  If so, the script will link the local
`module_utils/` files and directories inside the tox
venv `ansible/module_utils` so that the imports will be
found in the default pythonpath.
However
- this will not work outside of a venv, tox or otherwise,
unless you don't mind altering the system ansible install
- if there is already a …

ensure module_utils imports can be resolved

---

.yamllint.yml
molecule/default/molecule.yml
tox.ini

With molecule v3, the linter config needs to be changed. To prepare for
this, run yamllint with tox as molecule would do it for V3.
Note: extracted from https://github.com/linux-system-roles/network/pull/170

molecule/tox: Support yamllint without molecule

---

.gitignore
.travis/config.sh
.travis/custom.sh
.travis/runblack.sh
.travis/runcoveralls.sh
.travis/runflake8.sh
.travis/runpylint.sh
.travis/runpytest.sh
.travis/runsyspycmd.sh
.travis/utils.sh
.yamllint_custom.yml
molecule/default/molecule.yml
tox.ini

Make sure projects can use `.travis/config.sh` to override
settings in the CI scripts.
Have `$TOPDIR` set in `.travis/utils.sh` so that all scripts
and `.travis/config.sh` can use it.
Add some customizations for black and flake8.
Add more items to `.gitignore`
Make flake8 exclude `.tox` and `.venv`

improvements to let projects override defaults

---

.travis/custom.sh
.travis/runblack.sh
.travis/runcoveralls.sh
.travis/runflake8.sh
.travis/runpylint.sh
.travis/runpytest.sh
.travis/runsyspycmd.sh
.travis/utils.sh
tox.ini

Inside of venvs, just use the `python` command directly - the venv
should have configured `PATH` etc. to use the correct python and
environment.  Use `command -p python` to get the system python.

do not use envpython

---

.travis/config.sh
.travis/runcoveralls.sh
.travis/runflake8.sh
.travis/runpylint.sh
.travis/runpytest.sh
.travis/utils.sh
ansible26_requirements.txt
ansible_pytest_extra_requirements.txt
pytest26_extra_requirements.txt
pytest_extra_requirements.txt
tests/setup_module_utils.sh
tox.ini

use versioned dependencies in req files
clarify valid values for LSR_PUBLISH_COVERAGE
do setup_module_utils per-script with env. vars.
move flake8 args to [flake8] section of tox.ini
drop RUN_FLAKE8_IGNORE in favor of RUN_FLAKE8_EXTRA_ARGS
add license header

Several code cleanup issues for .travis/tox/tests code

---

.travis/runpylint.sh

Some of the RUN_PYLINT_* variables are evaluated in a python script. To
ensure that they are passed to it, they need to be exported.
Signed-off-by: Till Maas <opensource@till.name>
This is a cherry pick from https://github.com/linux-system-roles/network/pull/197

runpylint.sh: Export RUN_PYLINT_* variables

---

tox.ini

Run coveralls after the unit tests to ensure that coverage data is
available
This is a cherry-pick from the network role

Travis/tox: Run coveralls for all unit tests

---

tox.ini

As reported in https://github.com/tox-dev/tox-travis/issues/147, the
python factor in tox-travis needs to match the Travis python environment
and not the python version. Therefore, add a separate line.
This is a sync from https://github.com/linux-system-roles/network/pull/215

tox: Add travis config for 3.8-dev

---

tox.ini

Move several common options to testenv instead of base to simplify the
file and use normal tox inheritance.
There is probably more potential for simplification but these seem to be some easy cases.
sync from:
https://github.com/linux-system-roles/network/pull/216

tox: Move common options to testenv

---

README.md

We need to have a place for role authors to document
return values - variables that the role might set for the
playbook author to use in subsequent tasks.
@pcahyna @tyll

add a section for role return values

---

.yamllint_defaults.yml

yamllint now lets us configure the allowed boolean values in the truthy check. Let's enable it and allow the values that conform to Ansible doc standards: https://meetbot.fedoraproject.org/ansible-docs/2019-01-08/docs_working_group.2019-01-08-15.31.html

Enable truthy check, allow yes/no/true/false

---

meta/main.yml

bump min_ansible_version to 2.7

---

tasks/main.yml
vars/default.yml
vars/main.yml

For including vars files, use the new best practices from
https://github.com/oasis-roles/meta_standards#platform-specific-variables

use new vars files best practices

---

tests/tests_include_vars_from_parent.yml

Remove the case_sensitive=true parameter to the unique filter, not supported in older Jinja2. Case sensitivity is not necessary here.
See https://github.com/linux-system-roles/storage/issues/156

Make compatible with old Jinja2 (2.7)

---

.travis/runcollection.sh

Instead of setting an argument list to runcollection.sh in tox.ini,
it checks the availability in the runcollection.sh script and pass
the generated list to the tox test against the converted collections
format.
See also https://github.com/linux-system-roles/network/pull/304#discussion_r513001651.

runcollection.sh - stop passing an argument list

---

meta/main.yml

As far as I was able to find, ansible container is deprecated so there is no need to push it into the templates
https://github.com/ansible/ansible-container

Remove reference to deprecated ansible containers

---

tasks/main.yml

Change multiline YAML syntax to avoid warnings about line-length from Travis CI.

Fix line-length warnings in travis build

---

molecule/default/Dockerfile.j2
molecule/default/molecule.yml

Use the new vault.centos.org repos.  Fix the yum repo configs in the
image if necessary to use these new repos.
Use the standard centos images from the centos registry rather than
custom lsr images from dockerhub.
Add support for centos8.

Fix centos6 repos; use standard centos images; add centos8

---

.github/workflows/tox.yml

* Remove CentOS 6 build as it seems to be broken
* Add CentOS 8 image
* Remove ansible 2.7 as ansible-lint is no longer installable with it
* Build also on push to generate the build status icons in readme
* Use Python 3 packages with DNF for CentOS 8
https://github.com/linux-system-roles/crypto_policies/pull/4/

Unbreak Github Actions based on the work in crypto policies role

---

molecule/default/molecule.yml

This drops support for molecule v2.  It requires the linter sections.
In molecule v3, since we don't use the molecule linters, we have to
remove those sections.  This means you cannot use the molecule.yml
with molecule v2 anymore - you must use molecule v3.  This means you
need to update tox-lsr to version 2.0.0 or later:
https://github.com/linux-system-roles/tox-lsr/releases/tag/2.0.0
This also adds support for podman.  You can use
`LSR_MOLECULE_DRIVER=podman tox -e molecule`
to use `podman` instead of `docker`.

drop molecule v2 for molecule v3; support podman

---

tests/tests_include_vars_from_parent.yml

By default, tox fails the tests/tests_include_vars_from_parent.yml file because the copy module does not use `mode: preserve`.

Fix unset file permissions within the copy module

---

.github/workflows/changelog_to_tag.yml
README.md

Description:
When a new changelog section is added to CHANGELOG.md and pushed,
changelog_to_tag.yml is triggered, which generates a new tag and
a new release.
Example of CHANGELOG.md changes:
[9.9.9] - 2022-12-31
--------------------
- New feature A
- Bug fix B
Using this example, when the commit on CHANGELOG.md is pushed, a
new tag "9.9.9" is added and Version 9.9.9 is released in github.
If tag "9.9.9" already exists, the CHANGELOG.md push fails.
NOTE: Template is not tagged with any version yet. When it is,
please add CHANGELOG.md to the template top directory having the
following contents, where #.#.# is the initial version and YYYY-
MM-DD is the date adding the CHANGELOG.md. And the first two white
spaces are to be removed when create CHANGELOG.md.
Changelog
=========
[#.#.#] - …

[citest skip] Add changelog_to_tag.yml to .github/workflows

---

defaults/main.yml
vars/main.yml

I've removed the unnecessary quotings I could find in the template to match the [automation-good-practises](https://github.com/redhat-cop/automation-good-practices/blob/main/coding_style/README.adoc) that @richm cited in #81.
This PR should resolve #81.
Signed-off-by: Joerg Kastning <joerg.kastning@uni-bielefeld.de>

Removed unnecessary quotings

---

templates/foo.conf.j2

Add role name to the generated config files.
```
```
ote: This information is provided to help customers identify that it was generated by System Roles. It may also be used for future analysis.

Fingerprint RHEL System Role managed config files

---

README.md

Remove the `Dependencies` section.  We already have a `Requirements` section
and having a `Dependencies` section in addition is causing confusion.
Clarify what goes into the `Requirements` section.

docs: remove the Dependencies section

---

.ansible-lint
.ostree/README.md
.ostree/get_ostree_data.sh
.sanity-ansible-ignore-2.12.txt
.sanity-ansible-ignore-2.13.txt
.sanity-ansible-ignore-2.14.txt
.sanity-ansible-ignore-2.15.txt
.sanity-ansible-ignore-2.9.txt
README-ostree.md
README.md
meta/collection-requirements.yml
tasks/set_vars.yml

Feature: Allow running and testing the role with ostree managed nodes.
Reason: We have users who want to use the role to manage ostree
systems.
Result: Users can use the role to manage ostree managed nodes.
Signed-off-by: Rich Megginson <rmeggins@redhat.com>

feat: support for ostree systems

---

meta/main.yml
vars/CentOS_10.yml
vars/RedHat_10.yml

According to the Ansible team, support for listing platforms in
role `meta/main.yml` files is being removed.
Instead, they recommend using `galaxy_tags`
https://github.com/ansible/ansible/blob/stable-2.17/changelogs/CHANGELOG-v2.17.rst
"Remove the galaxy_info field platforms from the role templates"
https://github.com/ansible/ansible/issues/82453
Many roles already have tags such as "rhel", "redhat", "centos", and "fedora".
I propose that we ensure all of the system roles have these tags.
Some of our roles support Suse, Debian, Ubuntu, and others.
We should add tags for those e.g. the ssh role already has tags for "debian" and "ubuntu".
In addition - for each version listed under `platforms.EL` - add a tag like `elN`.
Q: Why not use a delimiter between the platform and the version e.g. …

fix: add support for EL10

---

.github/workflows/ansible-lint.yml
.github/workflows/ansible-managed-var-comment.yml
.github/workflows/ansible-test.yml
.github/workflows/qemu-kvm-integration-tests.yml
meta/main.yml

Feature: Support running this role during container builds and in
container environments.
Reason: This is particularly useful for building bootc derivative OSes.
It's also desirable to run roles in system containers.
Result: These flags enable running the container scenarios in CI, which
ensures that the role works in podman system containers as well as
buildah build environment and thus allows us to officially support this
role for image mode builds.
Actual roles may opt out of this by dropping the corresponding tag.

feat: Support this role in container environments and builds

---

.github/workflows/ansible-lint.yml
.github/workflows/ansible-managed-var-comment.yml
.github/workflows/ansible-test.yml
.github/workflows/build_docs.yml
.github/workflows/qemu-kvm-integration-tests.yml
.github/workflows/tft.yml

Add Fedora 42 to testing farm test matrix, drop Fedora 40
Use tox-lsr 3.9.0 for the `--lsr-report-errors-url` argument.
Add the argument `--lsr-report-errors-url DEFAULT` to the qemu test so that
the errors will be written to the output log.  This uses the output callback
https://github.com/linux-system-roles/auto-maintenance/blob/main/callback_plugins/lsr_report_errors.py
Use the check_logs.py script
https://github.com/linux-system-roles/auto-maintenance/blob/main/check_logs.py
with the `--github-action-format` argument to format the errors
in a github action friendly manner.
Rename the log files `-FAIL.log` or `-SUCCESS.log` depending on status.
This is compatible with the way the testing farm log files are named, and
makes it easy to tell if a test passed or failed from the log file …

ci: Add Fedora 42; use tox-lsr 3.9.0; use lsr-report-errors for qemu tests
